"""
digest_builder.py — Composes markdown and HTML digest from enriched articles.

No external API calls — pure formatting.
"""

from news_collector import TOPIC_LABELS

SECTION_COLORS = {
    "payments": "#0066cc",
    "ai_llm":   "#cc6600",
}


def build_markdown_digest(enriched: dict, date: str, x_posts: list = None) -> str:
    lines = [f"# DailyBrief — {date}\n"]

    for topic_key, articles in enriched.items():
        label = TOPIC_LABELS.get(topic_key, topic_key)
        lines.append(f"\n## {label}\n")

        if not articles:
            lines.append("_No articles found today._\n")
            continue

        for a in articles:
            title     = a.get("title", "Untitled")
            url       = a.get("url", "")
            summary   = a.get("summary", a.get("snippet", ""))
            published = a.get("published", "")
            source    = a.get("source", "")

            lines.append(f"### [{title}]({url})")
            if published or source:
                meta = " · ".join(filter(None, [source, published]))
                lines.append(f"_{meta}_\n")
            lines.append(f"{summary}\n")

    if x_posts:
        lines.append("\n## X — From People You Follow\n")
        for p in x_posts:
            lines.append(f"### [@{p['author']}]({p['url']})")
            lines.append(f"_❤️ {p['likes']} · 🔁 {p['retweets']} · {p['published']}_\n")
            lines.append(f"{p['text'][:280]}\n")

    lines.append("\n---\n_Generated by DailyBrief · PradOS_")
    return "\n".join(lines)


def build_html_digest(enriched: dict, date: str, x_posts: list = None) -> str:
    sections_html = ""
    for topic_key, articles in enriched.items():
        label  = TOPIC_LABELS.get(topic_key, topic_key)
        color  = SECTION_COLORS.get(topic_key, "#333")
        cards  = ""

        if not articles:
            cards = '<p style="color:#888;font-size:13px;">No articles found today.</p>'
        else:
            for a in articles:
                title     = _esc(a.get("title", "Untitled"))
                url       = _esc(a.get("url", "#"))
                summary   = _esc(a.get("summary", a.get("snippet", "")))
                published = _esc(a.get("published", ""))
                source    = _esc(a.get("source", ""))
                meta      = " · ".join(filter(None, [source, published]))

                cards += f"""
                <div style="background:#fff;border-left:4px solid {color};border-radius:6px;
                            padding:16px 20px;margin-bottom:14px;
                            box-shadow:0 1px 4px rgba(0,0,0,0.06);">
                  <a href="{url}" style="font-size:15px;font-weight:600;color:{color};
                                         text-decoration:none;line-height:1.4;display:block;
                                         margin-bottom:4px;">{title}</a>
                  {f'<p style="font-size:11px;color:#999;margin:0 0 8px;">{meta}</p>' if meta else ''}
                  <p style="font-size:13px;color:#444;line-height:1.6;margin:0 0 12px;">{summary}</p>
                  <a href="{url}" style="display:inline-block;font-size:11px;font-weight:600;
                                         color:#fff;background:{color};padding:5px 12px;
                                         border-radius:4px;text-decoration:none;">Read more →</a>
                </div>"""

        sections_html += f"""
        <div style="margin-bottom:32px;">
          <div style="background:{color};color:#fff;font-size:11px;font-weight:700;
                      letter-spacing:0.08em;text-transform:uppercase;
                      padding:8px 16px;border-radius:4px;margin-bottom:14px;">
            {label}
          </div>
          {cards}
        </div>"""

    # X section
    x_section_html = ""
    if x_posts:
        x_cards = ""
        for p in x_posts:
            author    = _esc(p.get("author", ""))
            text      = _esc(p.get("text", "")[:280])
            url       = _esc(p.get("url", "#"))
            published = _esc(p.get("published", ""))
            likes     = p.get("likes", 0)
            retweets  = p.get("retweets", 0)

            x_cards += f"""
            <div style="background:#fff;border-left:4px solid #1da1f2;border-radius:6px;
                        padding:16px 20px;margin-bottom:14px;
                        box-shadow:0 1px 4px rgba(0,0,0,0.06);">
              <a href="{url}" style="font-size:13px;font-weight:600;color:#1da1f2;
                                     text-decoration:none;">@{author}</a>
              <p style="font-size:11px;color:#999;margin:2px 0 8px;">
                ❤️ {likes} &nbsp; 🔁 {retweets} &nbsp; {published}
              </p>
              <p style="font-size:13px;color:#444;line-height:1.6;margin:0 0 10px;">{text}</p>
              <a href="{url}" style="display:inline-block;font-size:11px;font-weight:600;
                                     color:#fff;background:#1da1f2;padding:5px 12px;
                                     border-radius:4px;text-decoration:none;">View on X →</a>
            </div>"""

        x_section_html = f"""
        <div style="margin-bottom:32px;">
          <div style="background:#1da1f2;color:#fff;font-size:11px;font-weight:700;
                      letter-spacing:0.08em;text-transform:uppercase;
                      padding:8px 16px;border-radius:4px;margin-bottom:14px;">
            X — From People You Follow
          </div>
          {x_cards}
        </div>"""

    return f"""
    <!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background:#f4f4f4;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
      <div style="max-width:600px;margin:24px auto;background:#f4f4f4;">

        <!-- Header -->
        <div style="background:#1a1d27;border-radius:8px 8px 0 0;padding:20px 24px;
                    display:flex;align-items:center;justify-content:space-between;">
          <span style="color:#a78bfa;font-size:18px;font-weight:700;letter-spacing:0.02em;">
            DailyBrief
          </span>
          <span style="color:#64748b;font-size:12px;">{date}</span>
        </div>

        <!-- Body -->
        <div style="background:#f9f9f9;padding:24px;">
          {sections_html}
          {x_section_html}
        </div>

        <!-- Footer -->
        <div style="background:#1a1d27;border-radius:0 0 8px 8px;padding:12px 24px;
                    text-align:center;">
          <span style="color:#475569;font-size:11px;">Generated by DailyBrief · PradOS</span>
        </div>

      </div>
    </body>
    </html>"""


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;"))


if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(__file__))
    from news_collector import fetch_all_topics
    from summarizer import summarize_all
    from datetime import date

    today = date.today().strftime("%Y-%m-%d")
    raw      = fetch_all_topics()
    enriched = summarize_all(raw)

    md   = build_markdown_digest(enriched, today)
    html = build_html_digest(enriched, today)

    # Save preview files to _temp
    preview_html = os.path.join(os.path.dirname(__file__), "../../../_temp/digest-preview.html")
    preview_md   = os.path.join(os.path.dirname(__file__), "../../../_temp/digest-preview.md")

    with open(preview_html, "w") as f:
        f.write(html)
    with open(preview_md, "w") as f:
        f.write(md)

    print(f"\nPreview saved:")
    print(f"  HTML → _temp/digest-preview.html")
    print(f"  MD   → _temp/digest-preview.md")
    print("\n" + md[:800])
